# Generated by Django 5.0 on 2025-12-15 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desborde', 'Desborde Inminente'), ('gas', 'Nivel de Gas Alto'), ('temperatura', 'Temperatura Anormal'), ('falla_sensor', 'Falla de Sensor')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('mensaje', models.TextField()),
                ('valor_actual', models.DecimalField(decimal_places=2, help_text='Valor que disparó la alerta', max_digits=10)),
                ('umbral', models.DecimalField(decimal_places=2, help_text='Valor umbral configurado', max_digits=10)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True, default='')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='contenedores.contenedor')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['resuelta', '-creada_en'], name='alertas_resuelt_461b48_idx'), models.Index(fields=['prioridad', '-creada_en'], name='alertas_priorid_a58bd9_idx')],
            },
        ),
    ]
