# Generated by Django 5.0 on 2025-12-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
        ('contenedores', '0004_alter_contenedor_numero_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedor_alertas', to='contenedores.contenedor'),
        ),
    ]
