# Generated by Django 5.0 on 2025-12-15 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número del contenedor (1-22)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)])),
                ('nombre', models.CharField(help_text='Nombre o identificador', max_length=200)),
                ('direccion', models.TextField(help_text='Dirección exacta del contenedor')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud GPS', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud GPS', max_digits=9)),
                ('capacidad_litros', models.IntegerField(default=3300, help_text='Capacidad total en litros')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'db_table': 'contenedores',
                'ordering': ['numero'],
            },
        ),
    ]
