# Generated by Django 5.0 on 2026-01-23 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(editable=False, help_text='AUTO-GENERADO', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)])),
                ('nombre', models.CharField(help_text='Nombre o identificador del contenedor', max_length=200)),
                ('device_id', models.CharField(blank=True, help_text='ID del dispositivo IoT (ej: CONT_001, CONT_002)', max_length=100, null=True, unique=True)),
                ('direccion', models.TextField(help_text='Dirección exacta del contenedor')),
                ('latitud', models.DecimalField(decimal_places=6, help_text='Latitud GPS (Cochabamba: -17.393)', max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, help_text='Longitud GPS (Cochabamba: -66.157)', max_digits=9)),
                ('capacidad_litros', models.IntegerField(default=3300, help_text='Capacidad total en litros (3 compartimentos)', validators=[django.core.validators.MinValueValidator(100)])),
                ('nivel_actual_cache', models.IntegerField(default=0, help_text='Nivel actual en porcentaje (0-100) - Actualizado por IoT', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', help_text='Estado actual del contenedor', max_length=20)),
                ('fecha_instalacion', models.DateField(auto_now_add=True, help_text='Fecha de instalación del contenedor (AUTO-GENERADA)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name': 'Contenedor',
                'verbose_name_plural': 'Contenedores',
                'db_table': 'contenedores',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['estado'], name='contenedore_estado_f4f7e6_idx'), models.Index(fields=['numero'], name='contenedore_numero_44716c_idx'), models.Index(fields=['device_id'], name='contenedore_device__0cf517_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('critico', 'Crítico'), ('advertencia', 'Advertencia'), ('info', 'Información')], max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=20)),
                ('mensaje', models.TextField()),
                ('nivel_detectado', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='contenedores.contenedor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', help_text='ID del dispositivo ESP32', max_length=100)),
                ('nivel_llenado', models.IntegerField(help_text='Porcentaje de llenado (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('distancia_cm', models.FloatField(blank=True, help_text='Distancia medida por sensor ultrasónico en cm', null=True)),
                ('temperatura', models.FloatField(blank=True, help_text='Temperatura ambiente en °C', null=True)),
                ('humedad', models.FloatField(blank=True, help_text='Humedad relativa en %', null=True)),
                ('presion', models.FloatField(blank=True, help_text='Presión atmosférica en hPa', null=True)),
                ('air_quality', models.IntegerField(blank=True, help_text='Calidad del aire (0-500)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Momento de la lectura')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='contenedores.contenedor')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'db_table': 'lecturas_sensores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='lecturas_se_timesta_c59bc7_idx'), models.Index(fields=['contenedor', '-timestamp'], name='lecturas_se_contene_c33f7e_idx')],
            },
        ),
    ]
