# Generated by Django 5.0 on 2025-12-18 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización del registro'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='capacidad_litros',
            field=models.IntegerField(default=3300, help_text='Capacidad total en litros (3 compartimentos)', validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'Mantenimiento')], default='activo', help_text='Estado actual del contenedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_instalacion',
            field=models.DateField(blank=True, help_text='Fecha de instalación del contenedor', null=True),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='latitud',
            field=models.DecimalField(decimal_places=6, help_text='Latitud GPS (Cochabamba: -17.393)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='longitud',
            field=models.DecimalField(decimal_places=6, help_text='Longitud GPS (Cochabamba: -66.157)', max_digits=9),
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='nombre',
            field=models.CharField(help_text='Nombre o identificador del contenedor', max_length=200),
        ),
        migrations.AddIndex(
            model_name='contenedor',
            index=models.Index(fields=['estado'], name='contenedore_estado_f4f7e6_idx'),
        ),
        migrations.AddIndex(
            model_name='contenedor',
            index=models.Index(fields=['numero'], name='contenedore_numero_44716c_idx'),
        ),
    ]
