# Generated by Django 5.0 on 2025-12-20 02:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0002_alter_contenedor_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='fecha_instalacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de instalación del contenedor (AUTO-GENERADA)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenedor',
            name='numero',
            field=models.IntegerField(editable=False, help_text='Número del contenedor (1-22) - AUTO-GENERADO', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)]),
        ),
    ]
