# Generated by Django 5.0 on 2025-12-20 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenedores', '0003_alter_contenedor_fecha_instalacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='numero',
            field=models.IntegerField(editable=False, help_text='AUTO-GENERADO', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('critico', 'Crítico'), ('advertencia', 'Advertencia'), ('informativo', 'Informativo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nivel_actual', models.IntegerField(help_text='Nivel del contenedor cuando se generó la alerta')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='nueva', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='contenedores.contenedor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
