# Generated by Django 5.0 on 2025-12-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_llenado', models.DecimalField(decimal_places=2, help_text='Porcentaje de llenado (0-100%)', max_digits=5)),
                ('distancia_cm', models.DecimalField(decimal_places=2, help_text='Distancia medida en centímetros', max_digits=6)),
                ('temperatura', models.DecimalField(decimal_places=2, help_text='Temperatura en grados Celsius', max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, default=0, help_text='Humedad relativa en porcentaje', max_digits=5)),
                ('concentracion_gas', models.IntegerField(help_text='Concentración de gas en PPM (CO2/Metano)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='contenedores.contenedor')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'db_table': 'lecturas_sensores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['contenedor', '-timestamp'], name='lecturas_se_contene_c33f7e_idx'), models.Index(fields=['-timestamp'], name='lecturas_se_timesta_c59bc7_idx')],
            },
        ),
    ]
